# Generated by Django 3.0.5 on 2020-04-12 02:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apptodo', '0002_taskgrouplist_usergroup'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usergroup',
            unique_together={('member', 'group_name')},
        ),
    ]
